
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper 
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-producer:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: kafka-producer
      depends_on:
        - kafka

  spark:
    image: bitnami/spark:latest
    depends_on:
      - kafka
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042  
    volumes:
      - ./spark:/opt/spark-app
    entrypoint: ["/opt/spark-app/spark_app.py"]

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/init.cql:/init.cql 
    entrypoint: ["/bin/sh", "-c", "cassandra -f && until cqlsh -f /init.cql; do sleep 5; done"]

  flask_app:
    build: ./flask_app
    depends_on:
      - cassandra
    ports:
      - "5000:5000"

  mlflow:
    build: ./mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlruns
